<option value="Industrie" selected>Industrie</option>
<option value="Construction">Construction</option>
<option value="Commerce">Commerce</option>
<option value="Transports">Transports</option>
<option value="Hébergement et restauration">Hébergement et restauration</option>
<option value="Information et communication">Information et communication</option>
<option value="Activités financières et d'assurance">Activités financières et d'assurance</option>
<option value="Activités immobilières">Activités immobilières</option>
<option value="Activités spécialisées, scientifiques et techniques">Activités spécialisées, scientifiques et techniques</option>
<option value="Activités de services administratifs et de soutien">Activités de services administratifs et de soutien</option>
<option value="Santé et action sociale">Santé et action sociale</option>
<option value="Enseignement">Enseignement</option>
<option value="Arts, spectacles et activités récréatives">Arts, spectacles et activités récréatives</option>
<option value="Autres activités de services">Autres activités de services</option>
<option value="Agriculture, sylviculture et pêche">Agriculture, sylviculture et pêche</option>
<option value="Production et distribution d'énergie">Production et distribution d'énergie</option>
<option value="Eau, assainissement, gestion des déchets et dépollution">Eau, assainissement, gestion des déchets et dépollution</option>
<option value="Activités extractives">Activités extractives</option>
<option value="Télécommunications">Télécommunications</option>
<option value="Transport aérien">Transport aérien</option>
<option value="Transport maritime et fluvial">Transport maritime et fluvial</option>
<option value="Transport spatial">Transport spatial</option>
<option value="Transport par conduites">Transport par conduites</option>
<option value="Médias">Médias</option>
<option value="Logistique, entreposage et services auxiliaires des transports">Logistique, entreposage et services auxiliaires des transports</option>
<option value="Services informatiques">Services informatiques</option>
<option value="Ingénierie, recherche et développement">Ingénierie, recherche et développement</option>
<option value="Conseil et assistance aux entreprises">Conseil et assistance aux entreprises</option>
<option value="Immobilier commercial">Immobilier commercial</option>
<option value="Tourisme">Tourisme</option>
<option value="Industrie automobile">Industrie automobile</option>
