<option value="Afar (aar)">Afar (aar)</option>
<option value="Abkhazian (abk)">Abkhazian (abk)</option>
<option value="Achinese (ace)">Achinese (ace)</option>
<option value="Acoli (ach)">Acoli (ach)</option>
<option value="Adangme (ada)">Adangme (ada)</option>
<option value="Adyghe Adygei (ady)">Adyghe Adygei (ady)</option>
<option value="Afro-Asiatic languages (afa)">Afro-Asiatic languages (afa)</option>
<option value="Afrihili (afh)">Afrihili (afh)</option>
<option value="Afrikaans (afr)">Afrikaans (afr)</option>
<option value="Ainu (ain)">Ainu (ain)</option>
<option value="Akan (aka)">Akan (aka)</option>
<option value="Akkadian (akk)">Akkadian (akk)</option>
<option value="Albanian (alb)">Albanian (alb)</option>
<option value="Aleut (ale)">Aleut (ale)</option>
<option value="Algonquian languages (alg)">Algonquian languages (alg)</option>
<option value="Southern Altai (alt)">Southern Altai (alt)</option>
<option value="Amharic (amh)">Amharic (amh)</option>
<option value="English (ang)">English (ang)</option>
<option value="Angika (anp)">Angika (anp)</option>
<option value="Apache languages (apa)">Apache languages (apa)</option>
<option value="Arabic (ara)">Arabic (ara)</option>
<option value="Official Aramaic (700-300 BCE) Imperial Aramaic (700-300 BCE) (arc)">Official Aramaic (700-300 BCE) Imperial Aramaic (700-300 BCE) (arc)</option>
<option value="Aragonese (arg)">Aragonese (arg)</option>
<option value="Armenian (arm)">Armenian (arm)</option>
<option value="Mapudungun Mapuche (arn)">Mapudungun Mapuche (arn)</option>
<option value="Arapaho (arp)">Arapaho (arp)</option>
<option value="Artificial languages (art)">Artificial languages (art)</option>
<option value="Arawak (arw)">Arawak (arw)</option>
<option value="Assamese (asm)">Assamese (asm)</option>
<option value="Asturian Bable Leonese Asturleonese (ast)">Asturian Bable Leonese Asturleonese (ast)</option>
<option value="Athapascan languages (ath)">Athapascan languages (ath)</option>
<option value="Australian languages (aus)">Australian languages (aus)</option>
<option value="Avaric (ava)">Avaric (ava)</option>
<option value="Avestan (ave)">Avestan (ave)</option>
<option value="Awadhi (awa)">Awadhi (awa)</option>
<option value="Aymara (aym)">Aymara (aym)</option>
<option value="Azerbaijani (aze)">Azerbaijani (aze)</option>
<option value="Banda languages (bad)">Banda languages (bad)</option>
<option value="Bamileke languages (bai)">Bamileke languages (bai)</option>
<option value="Bashkir (bak)">Bashkir (bak)</option>
<option value="Baluchi (bal)">Baluchi (bal)</option>
<option value="Bambara (bam)">Bambara (bam)</option>
<option value="Balinese (ban)">Balinese (ban)</option>
<option value="Basque (baq)">Basque (baq)</option>
<option value="Basa (bas)">Basa (bas)</option>
<option value="Baltic languages (bat)">Baltic languages (bat)</option>
<option value="Beja Bedawiyet (bej)">Beja Bedawiyet (bej)</option>
<option value="Belarusian (bel)">Belarusian (bel)</option>
<option value="Bemba (bem)">Bemba (bem)</option>
<option value="Bengali (ben)">Bengali (ben)</option>
<option value="Berber languages (ber)">Berber languages (ber)</option>
<option value="Bhojpuri (bho)">Bhojpuri (bho)</option>
<option value="Bihari languages (bih)">Bihari languages (bih)</option>
<option value="Bikol (bik)">Bikol (bik)</option>
<option value="Bini Edo (bin)">Bini Edo (bin)</option>
<option value="Bislama (bis)">Bislama (bis)</option>
<option value="Siksika (bla)">Siksika (bla)</option>
<option value="Bantu (Other) (bnt)">Bantu (Other) (bnt)</option>
<option value="Bosnian (bos)">Bosnian (bos)</option>
<option value="Braj (bra)">Braj (bra)</option>
<option value="Breton (bre)">Breton (bre)</option>
<option value="Batak languages (btk)">Batak languages (btk)</option>
<option value="Buriat (bua)">Buriat (bua)</option>
<option value="Buginese (bug)">Buginese (bug)</option>
<option value="Bulgarian (bul)">Bulgarian (bul)</option>
<option value="Burmese (bur)">Burmese (bur)</option>
<option value="Blin Bilin (byn)">Blin Bilin (byn)</option>
<option value="Caddo (cad)">Caddo (cad)</option>
<option value="Central American Indian languages (cai)">Central American Indian languages (cai)</option>
<option value="Galibi Carib (car)">Galibi Carib (car)</option>
<option value="Catalan Valencian (cat)">Catalan Valencian (cat)</option>
<option value="Caucasian languages (cau)">Caucasian languages (cau)</option>
<option value="Cebuano (ceb)">Cebuano (ceb)</option>
<option value="Celtic languages (cel)">Celtic languages (cel)</option>
<option value="Chamorro (cha)">Chamorro (cha)</option>
<option value="Chibcha (chb)">Chibcha (chb)</option>
<option value="Chechen (che)">Chechen (che)</option>
<option value="Chagatai (chg)">Chagatai (chg)</option>
<option value="Chinese (chi)">Chinese (chi)</option>
<option value="Chuukese (chk)">Chuukese (chk)</option>
<option value="Mari (chm)">Mari (chm)</option>
<option value="Chinook jargon (chn)">Chinook jargon (chn)</option>
<option value="Choctaw (cho)">Choctaw (cho)</option>
<option value="Chipewyan Dene Suline (chp)">Chipewyan Dene Suline (chp)</option>
<option value="Cherokee (chr)">Cherokee (chr)</option>
<option value="Church Slavic Old Slavonic Church Slavonic Old Bulgarian Old Church Slavonic (chu)">Church Slavic Old Slavonic Church Slavonic Old Bulgarian Old Church Slavonic (chu)</option>
<option value="Chuvash (chv)">Chuvash (chv)</option>
<option value="Cheyenne (chy)">Cheyenne (chy)</option>
<option value="Chamic languages (cmc)">Chamic languages (cmc)</option>
<option value="Coptic (cop)">Coptic (cop)</option>
<option value="Cornish (cor)">Cornish (cor)</option>
<option value="Corsican (cos)">Corsican (cos)</option>
<option value="Creoles and pidgins (cpe)">Creoles and pidgins (cpe)</option>
<option value="Creoles and pidgins (cpf)">Creoles and pidgins (cpf)</option>
<option value="Creoles and pidgins (cpp)">Creoles and pidgins (cpp)</option>
<option value="Cree (cre)">Cree (cre)</option>
<option value="Crimean Tatar Crimean Turkish (crh)">Crimean Tatar Crimean Turkish (crh)</option>
<option value="Creoles and pidgins  (crp)">Creoles and pidgins  (crp)</option>
<option value="Kashubian (csb)">Kashubian (csb)</option>
<option value="Cushitic languages (cus)">Cushitic languages (cus)</option>
<option value="Czech (cze)">Czech (cze)</option>
<option value="Dakota (dak)">Dakota (dak)</option>
<option value="Danish (dan)">Danish (dan)</option>
<option value="Dargwa (dar)">Dargwa (dar)</option>
<option value="Land Dayak languages (day)">Land Dayak languages (day)</option>
<option value="Delaware (del)">Delaware (del)</option>
<option value="Slave (Athapascan) (den)">Slave (Athapascan) (den)</option>
<option value="Dogrib (dgr)">Dogrib (dgr)</option>
<option value="Dinka (din)">Dinka (din)</option>
<option value="Divehi Dhivehi Maldivian (div)">Divehi Dhivehi Maldivian (div)</option>
<option value="Dogri (doi)">Dogri (doi)</option>
<option value="Dravidian languages (dra)">Dravidian languages (dra)</option>
<option value="Lower Sorbian (dsb)">Lower Sorbian (dsb)</option>
<option value="Duala (dua)">Duala (dua)</option>
<option value="Dutch (dum)">Dutch (dum)</option>
<option value="Dutch Flemish (dut)">Dutch Flemish (dut)</option>
<option value="Dyula (dyu)">Dyula (dyu)</option>
<option value="Dzongkha (dzo)">Dzongkha (dzo)</option>
<option value="Efik (efi)">Efik (efi)</option>
<option value="Egyptian (Ancient) (egy)">Egyptian (Ancient) (egy)</option>
<option value="Ekajuk (eka)">Ekajuk (eka)</option>
<option value="Elamite (elx)">Elamite (elx)</option>
<option value="English (eng)">English (eng)</option>
<option value="English (enm)">English (enm)</option>
<option value="Esperanto (epo)">Esperanto (epo)</option>
<option value="Estonian (est)">Estonian (est)</option>
<option value="Ewe (ewe)">Ewe (ewe)</option>
<option value="Ewondo (ewo)">Ewondo (ewo)</option>
<option value="Fang (fan)">Fang (fan)</option>
<option value="Faroese (fao)">Faroese (fao)</option>
<option value="Fanti (fat)">Fanti (fat)</option>
<option value="Fijian (fij)">Fijian (fij)</option>
<option value="Filipino Pilipino (fil)">Filipino Pilipino (fil)</option>
<option value="Finnish (fin)">Finnish (fin)</option>
<option value="Finno-Ugrian languages (fiu)">Finno-Ugrian languages (fiu)</option>
<option value="Fon (fon)">Fon (fon)</option>
<option value="French (fre)">French (fre)</option>
<option value="French (frm)">French (frm)</option>
<option value="French (fro)">French (fro)</option>
<option value="Northern Frisian (frr)">Northern Frisian (frr)</option>
<option value="Eastern Frisian (frs)">Eastern Frisian (frs)</option>
<option value="Western Frisian (fry)">Western Frisian (fry)</option>
<option value="Fulah (ful)">Fulah (ful)</option>
<option value="Friulian (fur)">Friulian (fur)</option>
<option value="Ga (gaa)">Ga (gaa)</option>
<option value="Gayo (gay)">Gayo (gay)</option>
<option value="Gbaya (gba)">Gbaya (gba)</option>
<option value="Germanic languages (gem)">Germanic languages (gem)</option>
<option value="Georgian (geo)">Georgian (geo)</option>
<option value="German (ger)">German (ger)</option>
<option value="Geez (gez)">Geez (gez)</option>
<option value="Gilbertese (gil)">Gilbertese (gil)</option>
<option value="Gaelic Scottish Gaelic (gla)">Gaelic Scottish Gaelic (gla)</option>
<option value="Irish (gle)">Irish (gle)</option>
<option value="Galician (glg)">Galician (glg)</option>
<option value="Manx (glv)">Manx (glv)</option>
<option value="German (gmh)">German (gmh)</option>
<option value="German (goh)">German (goh)</option>
<option value="Gondi (gon)">Gondi (gon)</option>
<option value="Gorontalo (gor)">Gorontalo (gor)</option>
<option value="Gothic (got)">Gothic (got)</option>
<option value="Grebo (grb)">Grebo (grb)</option>
<option value="Greek (grc)">Greek (grc)</option>
<option value="Greek (gre)">Greek (gre)</option>
<option value="Guarani (grn)">Guarani (grn)</option>
<option value="Swiss German Alemannic Alsatian (gsw)">Swiss German Alemannic Alsatian (gsw)</option>
<option value="Gujarati (guj)">Gujarati (guj)</option>
<option value="Gwich'in (gwi)">Gwich'in (gwi)</option>
<option value="Haida (hai)">Haida (hai)</option>
<option value="Haitian Haitian Creole (hat)">Haitian Haitian Creole (hat)</option>
<option value="Hausa (hau)">Hausa (hau)</option>
<option value="Hawaiian (haw)">Hawaiian (haw)</option>
<option value="Hebrew (heb)">Hebrew (heb)</option>
<option value="Herero (her)">Herero (her)</option>
<option value="Hiligaynon (hil)">Hiligaynon (hil)</option>
<option value="Himachali languages Western Pahari languages (him)">Himachali languages Western Pahari languages (him)</option>
<option value="Hindi (hin)">Hindi (hin)</option>
<option value="Hittite (hit)">Hittite (hit)</option>
<option value="Hmong Mong (hmn)">Hmong Mong (hmn)</option>
<option value="Hiri Motu (hmo)">Hiri Motu (hmo)</option>
<option value="Croatian (hrv)">Croatian (hrv)</option>
<option value="Upper Sorbian (hsb)">Upper Sorbian (hsb)</option>
<option value="Hungarian (hun)">Hungarian (hun)</option>
<option value="Hupa (hup)">Hupa (hup)</option>
<option value="Iban (iba)">Iban (iba)</option>
<option value="Igbo (ibo)">Igbo (ibo)</option>
<option value="Icelandic (ice)">Icelandic (ice)</option>
<option value="Ido (ido)">Ido (ido)</option>
<option value="Sichuan Yi Nuosu (iii)">Sichuan Yi Nuosu (iii)</option>
<option value="Ijo languages (ijo)">Ijo languages (ijo)</option>
<option value="Inuktitut (iku)">Inuktitut (iku)</option>
<option value="Interlingue Occidental (ile)">Interlingue Occidental (ile)</option>
<option value="Iloko (ilo)">Iloko (ilo)</option>
<option value="Interlingua (International Auxiliary Language Association) (ina)">Interlingua (International Auxiliary Language Association) (ina)</option>
<option value="Indic languages (inc)">Indic languages (inc)</option>
<option value="Indonesian (ind)">Indonesian (ind)</option>
<option value="Indo-European languages (ine)">Indo-European languages (ine)</option>
<option value="Ingush (inh)">Ingush (inh)</option>
<option value="Inupiaq (ipk)">Inupiaq (ipk)</option>
<option value="Iranian languages (ira)">Iranian languages (ira)</option>
<option value="Iroquoian languages (iro)">Iroquoian languages (iro)</option>
<option value="Italian (ita)">Italian (ita)</option>
<option value="Javanese (jav)">Javanese (jav)</option>
<option value="Lojban (jbo)">Lojban (jbo)</option>
<option value="Japanese (jpn)">Japanese (jpn)</option>
<option value="Judeo-Persian (jpr)">Judeo-Persian (jpr)</option>
<option value="Judeo-Arabic (jrb)">Judeo-Arabic (jrb)</option>
<option value="Kara-Kalpak (kaa)">Kara-Kalpak (kaa)</option>
<option value="Kabyle (kab)">Kabyle (kab)</option>
<option value="Kachin Jingpho (kac)">Kachin Jingpho (kac)</option>
<option value="Kalaallisut Greenlandic (kal)">Kalaallisut Greenlandic (kal)</option>
<option value="Kamba (kam)">Kamba (kam)</option>
<option value="Kannada (kan)">Kannada (kan)</option>
<option value="Karen languages (kar)">Karen languages (kar)</option>
<option value="Kashmiri (kas)">Kashmiri (kas)</option>
<option value="Kanuri (kau)">Kanuri (kau)</option>
<option value="Kawi (kaw)">Kawi (kaw)</option>
<option value="Kazakh (kaz)">Kazakh (kaz)</option>
<option value="Kabardian (kbd)">Kabardian (kbd)</option>
<option value="Khasi (kha)">Khasi (kha)</option>
<option value="Khoisan languages (khi)">Khoisan languages (khi)</option>
<option value="Central Khmer (khm)">Central Khmer (khm)</option>
<option value="Khotanese Sakan (kho)">Khotanese Sakan (kho)</option>
<option value="Kikuyu Gikuyu (kik)">Kikuyu Gikuyu (kik)</option>
<option value="Kinyarwanda (kin)">Kinyarwanda (kin)</option>
<option value="Kirghiz Kyrgyz (kir)">Kirghiz Kyrgyz (kir)</option>
<option value="Kimbundu (kmb)">Kimbundu (kmb)</option>
<option value="Konkani (kok)">Konkani (kok)</option>
<option value="Komi (kom)">Komi (kom)</option>
<option value="Kongo (kon)">Kongo (kon)</option>
<option value="Korean (kor)">Korean (kor)</option>
<option value="Kosraean (kos)">Kosraean (kos)</option>
<option value="Kpelle (kpe)">Kpelle (kpe)</option>
<option value="Karachay-Balkar (krc)">Karachay-Balkar (krc)</option>
<option value="Karelian (krl)">Karelian (krl)</option>
<option value="Kru languages (kro)">Kru languages (kro)</option>
<option value="Kurukh (kru)">Kurukh (kru)</option>
<option value="Kuanyama Kwanyama (kua)">Kuanyama Kwanyama (kua)</option>
<option value="Kumyk (kum)">Kumyk (kum)</option>
<option value="Kurdish (kur)">Kurdish (kur)</option>
<option value="Kutenai (kut)">Kutenai (kut)</option>
<option value="Ladino (lad)">Ladino (lad)</option>
<option value="Lahnda (lah)">Lahnda (lah)</option>
<option value="Lamba (lam)">Lamba (lam)</option>
<option value="Lao (lao)">Lao (lao)</option>
<option value="Latin (lat)">Latin (lat)</option>
<option value="Latvian (lav)">Latvian (lav)</option>
<option value="Lezghian (lez)">Lezghian (lez)</option>
<option value="Limburgan Limburger Limburgish (lim)">Limburgan Limburger Limburgish (lim)</option>
<option value="Lingala (lin)">Lingala (lin)</option>
<option value="Lithuanian (lit)">Lithuanian (lit)</option>
<option value="Mongo (lol)">Mongo (lol)</option>
<option value="Lozi (loz)">Lozi (loz)</option>
<option value="Luxembourgish Letzeburgesch (ltz)">Luxembourgish Letzeburgesch (ltz)</option>
<option value="Luba-Lulua (lua)">Luba-Lulua (lua)</option>
<option value="Luba-Katanga (lub)">Luba-Katanga (lub)</option>
<option value="Ganda (lug)">Ganda (lug)</option>
<option value="Luiseno (lui)">Luiseno (lui)</option>
<option value="Lunda (lun)">Lunda (lun)</option>
<option value="Luo (Kenya and Tanzania) (luo)">Luo (Kenya and Tanzania) (luo)</option>
<option value="Lushai (lus)">Lushai (lus)</option>
<option value="Macedonian (mac)">Macedonian (mac)</option>
<option value="Madurese (mad)">Madurese (mad)</option>
<option value="Magahi (mag)">Magahi (mag)</option>
<option value="Marshallese (mah)">Marshallese (mah)</option>
<option value="Maithili (mai)">Maithili (mai)</option>
<option value="Makasar (mak)">Makasar (mak)</option>
<option value="Malayalam (mal)">Malayalam (mal)</option>
<option value="Mandingo (man)">Mandingo (man)</option>
<option value="Maori (mao)">Maori (mao)</option>
<option value="Austronesian languages (map)">Austronesian languages (map)</option>
<option value="Marathi (mar)">Marathi (mar)</option>
<option value="Masai (mas)">Masai (mas)</option>
<option value="Malay (may)">Malay (may)</option>
<option value="Moksha (mdf)">Moksha (mdf)</option>
<option value="Mandar (mdr)">Mandar (mdr)</option>
<option value="Mende (men)">Mende (men)</option>
<option value="Irish (mga)">Irish (mga)</option>
<option value="Mi'kmaq Micmac (mic)">Mi'kmaq Micmac (mic)</option>
<option value="Minangkabau (min)">Minangkabau (min)</option>
<option value="Uncoded languages (mis)">Uncoded languages (mis)</option>
<option value="Mon-Khmer languages (mkh)">Mon-Khmer languages (mkh)</option>
<option value="Malagasy (mlg)">Malagasy (mlg)</option>
<option value="Maltese (mlt)">Maltese (mlt)</option>
<option value="Manchu (mnc)">Manchu (mnc)</option>
<option value="Manipuri (mni)">Manipuri (mni)</option>
<option value="Manobo languages (mno)">Manobo languages (mno)</option>
<option value="Mohawk (moh)">Mohawk (moh)</option>
<option value="Mongolian (mon)">Mongolian (mon)</option>
<option value="Mossi (mos)">Mossi (mos)</option>
<option value="Multiple languages (mul)">Multiple languages (mul)</option>
<option value="Munda languages (mun)">Munda languages (mun)</option>
<option value="Creek (mus)">Creek (mus)</option>
<option value="Mirandese (mwl)">Mirandese (mwl)</option>
<option value="Marwari (mwr)">Marwari (mwr)</option>
<option value="Mayan languages (myn)">Mayan languages (myn)</option>
<option value="Erzya (myv)">Erzya (myv)</option>
<option value="Nahuatl languages (nah)">Nahuatl languages (nah)</option>
<option value="North American Indian languages (nai)">North American Indian languages (nai)</option>
<option value="Neapolitan (nap)">Neapolitan (nap)</option>
<option value="Nauru (nau)">Nauru (nau)</option>
<option value="Navajo Navaho (nav)">Navajo Navaho (nav)</option>
<option value="Ndebele (nbl)">Ndebele (nbl)</option>
<option value="Ndebele (nde)">Ndebele (nde)</option>
<option value="Ndonga (ndo)">Ndonga (ndo)</option>
<option value="Low German Low Saxon German (nds)">Low German Low Saxon German (nds)</option>
<option value="Nepali (nep)">Nepali (nep)</option>
<option value="Nepal Bhasa Newari (new)">Nepal Bhasa Newari (new)</option>
<option value="Nias (nia)">Nias (nia)</option>
<option value="Niger-Kordofanian languages (nic)">Niger-Kordofanian languages (nic)</option>
<option value="Niuean (niu)">Niuean (niu)</option>
<option value="Norwegian Nynorsk Nynorsk (nno)">Norwegian Nynorsk Nynorsk (nno)</option>
<option value="Bokmål (nob)">Bokmål (nob)</option>
<option value="Nogai (nog)">Nogai (nog)</option>
<option value="Norse (non)">Norse (non)</option>
<option value="Norwegian (nor)">Norwegian (nor)</option>
<option value="N'Ko (nqo)">N'Ko (nqo)</option>
<option value="Pedi Sepedi Northern Sotho (nso)">Pedi Sepedi Northern Sotho (nso)</option>
<option value="Nubian languages (nub)">Nubian languages (nub)</option>
<option value="Classical Newari Old Newari Classical Nepal Bhasa (nwc)">Classical Newari Old Newari Classical Nepal Bhasa (nwc)</option>
<option value="Chichewa Chewa Nyanja (nya)">Chichewa Chewa Nyanja (nya)</option>
<option value="Nyamwezi (nym)">Nyamwezi (nym)</option>
<option value="Nyankole (nyn)">Nyankole (nyn)</option>
<option value="Nyoro (nyo)">Nyoro (nyo)</option>
<option value="Nzima (nzi)">Nzima (nzi)</option>
<option value="Occitan (post 1500) Provençal (oci)">Occitan (post 1500) Provençal (oci)</option>
<option value="Ojibwa (oji)">Ojibwa (oji)</option>
<option value="Oriya (ori)">Oriya (ori)</option>
<option value="Oromo (orm)">Oromo (orm)</option>
<option value="Osage (osa)">Osage (osa)</option>
<option value="Ossetian Ossetic (oss)">Ossetian Ossetic (oss)</option>
<option value="Turkish (ota)">Turkish (ota)</option>
<option value="Otomian languages (oto)">Otomian languages (oto)</option>
<option value="Papuan languages (paa)">Papuan languages (paa)</option>
<option value="Pangasinan (pag)">Pangasinan (pag)</option>
<option value="Pahlavi (pal)">Pahlavi (pal)</option>
<option value="Pampanga Kapampangan (pam)">Pampanga Kapampangan (pam)</option>
<option value="Panjabi Punjabi (pan)">Panjabi Punjabi (pan)</option>
<option value="Papiamento (pap)">Papiamento (pap)</option>
<option value="Palauan (pau)">Palauan (pau)</option>
<option value="Persian (peo)">Persian (peo)</option>
<option value="Persian (per)">Persian (per)</option>
<option value="Philippine languages (phi)">Philippine languages (phi)</option>
<option value="Phoenician (phn)">Phoenician (phn)</option>
<option value="Pali (pli)">Pali (pli)</option>
<option value="Polish (pol)">Polish (pol)</option>
<option value="Pohnpeian (pon)">Pohnpeian (pon)</option>
<option value="Portuguese (por)">Portuguese (por)</option>
<option value="Prakrit languages (pra)">Prakrit languages (pra)</option>
<option value="Provençal (pro)">Provençal (pro)</option>
<option value="Pushto Pashto (pus)">Pushto Pashto (pus)</option>
<option value=tz"> Reserved for local use (qaa)"-tz"> Reserved for local use (qaa)</option>
<option value="Quechua (que)">Quechua (que)</option>
<option value="Rajasthani (raj)">Rajasthani (raj)</option>
<option value="Rapanui (rap)">Rapanui (rap)</option>
<option value="Rarotongan Cook Islands Maori (rar)">Rarotongan Cook Islands Maori (rar)</option>
<option value="Romance languages (roa)">Romance languages (roa)</option>
<option value="Romansh (roh)">Romansh (roh)</option>
<option value="Romany (rom)">Romany (rom)</option>
<option value="Romanian Moldavian Moldovan (rum)">Romanian Moldavian Moldovan (rum)</option>
<option value="Rundi (run)">Rundi (run)</option>
<option value="Aromanian Arumanian Macedo-Romanian (rup)">Aromanian Arumanian Macedo-Romanian (rup)</option>
<option value="Russian (rus)">Russian (rus)</option>
<option value="Sandawe (sad)">Sandawe (sad)</option>
<option value="Sango (sag)">Sango (sag)</option>
<option value="Yakut (sah)">Yakut (sah)</option>
<option value="South American Indian (Other) (sai)">South American Indian (Other) (sai)</option>
<option value="Salishan languages (sal)">Salishan languages (sal)</option>
<option value="Samaritan Aramaic (sam)">Samaritan Aramaic (sam)</option>
<option value="Sanskrit (san)">Sanskrit (san)</option>
<option value="Sasak (sas)">Sasak (sas)</option>
<option value="Santali (sat)">Santali (sat)</option>
<option value="Sicilian (scn)">Sicilian (scn)</option>
<option value="Scots (sco)">Scots (sco)</option>
<option value="Selkup (sel)">Selkup (sel)</option>
<option value="Semitic languages (sem)">Semitic languages (sem)</option>
<option value="Irish (sga)">Irish (sga)</option>
<option value="Sign Languages (sgn)">Sign Languages (sgn)</option>
<option value="Shan (shn)">Shan (shn)</option>
<option value="Sidamo (sid)">Sidamo (sid)</option>
<option value="Sinhala Sinhalese (sin)">Sinhala Sinhalese (sin)</option>
<option value="Siouan languages (sio)">Siouan languages (sio)</option>
<option value="Sino-Tibetan languages (sit)">Sino-Tibetan languages (sit)</option>
<option value="Slavic languages (sla)">Slavic languages (sla)</option>
<option value="Slovak (slo)">Slovak (slo)</option>
<option value="Slovenian (slv)">Slovenian (slv)</option>
<option value="Southern Sami (sma)">Southern Sami (sma)</option>
<option value="Northern Sami (sme)">Northern Sami (sme)</option>
<option value="Sami languages (smi)">Sami languages (smi)</option>
<option value="Lule Sami (smj)">Lule Sami (smj)</option>
<option value="Inari Sami (smn)">Inari Sami (smn)</option>
<option value="Samoan (smo)">Samoan (smo)</option>
<option value="Skolt Sami (sms)">Skolt Sami (sms)</option>
<option value="Shona (sna)">Shona (sna)</option>
<option value="Sindhi (snd)">Sindhi (snd)</option>
<option value="Soninke (snk)">Soninke (snk)</option>
<option value="Sogdian (sog)">Sogdian (sog)</option>
<option value="Somali (som)">Somali (som)</option>
<option value="Songhai languages (son)">Songhai languages (son)</option>
<option value="Sotho (sot)">Sotho (sot)</option>
<option value="Spanish Castilian (spa)">Spanish Castilian (spa)</option>
<option value="Sardinian (srd)">Sardinian (srd)</option>
<option value="Sranan Tongo (srn)">Sranan Tongo (srn)</option>
<option value="Serbian (srp)">Serbian (srp)</option>
<option value="Serer (srr)">Serer (srr)</option>
<option value="Nilo-Saharan languages (ssa)">Nilo-Saharan languages (ssa)</option>
<option value="Swati (ssw)">Swati (ssw)</option>
<option value="Sukuma (suk)">Sukuma (suk)</option>
<option value="Sundanese (sun)">Sundanese (sun)</option>
<option value="Susu (sus)">Susu (sus)</option>
<option value="Sumerian (sux)">Sumerian (sux)</option>
<option value="Swahili (swa)">Swahili (swa)</option>
<option value="Swedish (swe)">Swedish (swe)</option>
<option value="Classical Syriac (syc)">Classical Syriac (syc)</option>
<option value="Syriac (syr)">Syriac (syr)</option>
<option value="Tahitian (tah)">Tahitian (tah)</option>
<option value="Tai languages (tai)">Tai languages (tai)</option>
<option value="Tamil (tam)">Tamil (tam)</option>
<option value="Tatar (tat)">Tatar (tat)</option>
<option value="Telugu (tel)">Telugu (tel)</option>
<option value="Timne (tem)">Timne (tem)</option>
<option value="Tereno (ter)">Tereno (ter)</option>
<option value="Tetum (tet)">Tetum (tet)</option>
<option value="Tajik (tgk)">Tajik (tgk)</option>
<option value="Tagalog (tgl)">Tagalog (tgl)</option>
<option value="Thai (tha)">Thai (tha)</option>
<option value="Tibetan (tib)">Tibetan (tib)</option>
<option value="Tigre (tig)">Tigre (tig)</option>
<option value="Tigrinya (tir)">Tigrinya (tir)</option>
<option value="Tiv (tiv)">Tiv (tiv)</option>
<option value="Tokelau (tkl)">Tokelau (tkl)</option>
<option value="Klingon tlhIngan-Hol (tlh)">Klingon tlhIngan-Hol (tlh)</option>
<option value="Tlingit (tli)">Tlingit (tli)</option>
<option value="Tamashek (tmh)">Tamashek (tmh)</option>
<option value="Tonga (Nyasa) (tog)">Tonga (Nyasa) (tog)</option>
<option value="Tonga (Tonga Islands) (ton)">Tonga (Tonga Islands) (ton)</option>
<option value="Tok Pisin (tpi)">Tok Pisin (tpi)</option>
<option value="Tsimshian (tsi)">Tsimshian (tsi)</option>
<option value="Tswana (tsn)">Tswana (tsn)</option>
<option value="Tsonga (tso)">Tsonga (tso)</option>
<option value="Turkmen (tuk)">Turkmen (tuk)</option>
<option value="Tumbuka (tum)">Tumbuka (tum)</option>
<option value="Tupi languages (tup)">Tupi languages (tup)</option>
<option value="Turkish (tur)">Turkish (tur)</option>
<option value="Altaic languages (tut)">Altaic languages (tut)</option>
<option value="Tuvalu (tvl)">Tuvalu (tvl)</option>
<option value="Twi (twi)">Twi (twi)</option>
<option value="Tuvinian (tyv)">Tuvinian (tyv)</option>
<option value="Udmurt (udm)">Udmurt (udm)</option>
<option value="Ugaritic (uga)">Ugaritic (uga)</option>
<option value="Uighur Uyghur (uig)">Uighur Uyghur (uig)</option>
<option value="Ukrainian (ukr)">Ukrainian (ukr)</option>
<option value="Umbundu (umb)">Umbundu (umb)</option>
<option value="Undetermined (und)">Undetermined (und)</option>
<option value="Urdu (urd)">Urdu (urd)</option>
<option value="Uzbek (uzb)">Uzbek (uzb)</option>
<option value="Vai (vai)">Vai (vai)</option>
<option value="Venda (ven)">Venda (ven)</option>
<option value="Vietnamese (vie)">Vietnamese (vie)</option>
<option value="Volapük (vol)">Volapük (vol)</option>
<option value="Votic (vot)">Votic (vot)</option>
<option value="Wakashan languages (wak)">Wakashan languages (wak)</option>
<option value="Walamo (wal)">Walamo (wal)</option>
<option value="Waray (war)">Waray (war)</option>
<option value="Washo (was)">Washo (was)</option>
<option value="Welsh (wel)">Welsh (wel)</option>
<option value="Sorbian languages (wen)">Sorbian languages (wen)</option>
<option value="Walloon (wln)">Walloon (wln)</option>
<option value="Wolof (wol)">Wolof (wol)</option>
<option value="Kalmyk Oirat (xal)">Kalmyk Oirat (xal)</option>
<option value="Xhosa (xho)">Xhosa (xho)</option>
<option value="Yao (yao)">Yao (yao)</option>
<option value="Yapese (yap)">Yapese (yap)</option>
<option value="Yiddish (yid)">Yiddish (yid)</option>
<option value="Yoruba (yor)">Yoruba (yor)</option>
<option value="Yupik languages (ypk)">Yupik languages (ypk)</option>
<option value="Zapotec (zap)">Zapotec (zap)</option>
<option value="Blissymbols Blissymbolics Bliss (zbl)">Blissymbols Blissymbolics Bliss (zbl)</option>
<option value="Zenaga (zen)">Zenaga (zen)</option>
<option value="Zhuang Chuang (zha)">Zhuang Chuang (zha)</option>
<option value="Zande languages (znd)">Zande languages (znd)</option>
<option value="Zulu (zul)">Zulu (zul)</option>
<option value="Zuni (zun)">Zuni (zun)</option>
<option value="No linguistic content Not applicable (zxx)">No linguistic content Not applicable (zxx)</option>
<option value="Zaza Dimili Dimli Kirdki Kirmanjki Zazaki (zza)">Zaza Dimili Dimli Kirdki Kirmanjki Zazaki (zza)</option>
